# Generated by Django 5.2.12 on 2026-03-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("gold_price", "Gold Price"),
                            ("silver_price", "Silver Price"),
                            ("oil_price", "Oil Price"),
                            ("treasury_10y", "US 10Y Treasury"),
                            ("dow_gold_ratio", "Dow/Gold Ratio"),
                            ("rss_feed", "RSS Feed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("grid_x", models.PositiveIntegerField(default=0)),
                ("grid_y", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=1)),
                ("height", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=300)),
            ],
            options={
                "ordering": ["grid_y", "grid_x"],
            },
        ),
        migrations.CreateModel(
            name="KeyboardShortcut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=200)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("focus_widget", "Focus Widget"),
                            ("expand_widget", "Expand Widget"),
                            ("refresh_widget", "Refresh Widget"),
                            ("next_widget", "Next Widget"),
                            ("previous_widget", "Previous Widget"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_widget",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
